# Generated by Django 4.2.25 on 2025-10-24 13:17

from django.db import migrations


def set_default_game(apps, schema_editor):
    Review = apps.get_model('blog', 'Review')
    Game = apps.get_model('blog', 'Game')

    default_game, _ = Game.objects.get_or_create(
        title='Unknown',
        defaults={
            'platform': 'Unknown',
            'release_year': 0,
            'developer': 'Unknown',
            'publisher': 'Unknown',
            'description': 'Placeholder',
        }
    )

    Review.objects.filter(game__isnull=True).update(game=default_game)


def unset_default_game(apps, schema_editor):
    Review = apps.get_model('blog', 'Review')
    Review.objects.update(game=None)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_game_comment_review_game'),
    ]

    operations = [
        migrations.RunPython(set_default_game, unset_default_game),
    ]
