# Generated by Django 4.2.25 on 2025-10-29 13:58

from django.db import migrations
from django.utils.text import slugify


def generate_unique_slug(model, base_value, slug_field='slug'):
    base = slugify(base_value)[:190]
    slug = base
    suffix = 1
    while model.objects.filter(**{slug_field: slug}).exists():
        slug = f"{base}-{suffix}"
        suffix += 1
    return slug


def forwards(apps, schema_editor):
    Game = apps.get_model('blog', 'Game')
    Review = apps.get_model('blog', 'Review')

    for g in Game.objects.all():
        if not g.slug:
            g.slug = generate_unique_slug(Game, g.title)
            g.save(update_fields=['slug'])

    for r in Review.objects.all():
        if not r.slug:
            base = r.title or f"review-{r.pk}"
            r.slug = generate_unique_slug(Review, base)
            r.save(update_fields=['slug'])


def backwards(apps, schema_editor):
    Game = apps.get_model('blog', 'Game')
    Review = apps.get_model('blog', 'Review')
    Game.objects.update(slug=None)
    Review.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_review_options_game_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
