# Generated by Django 4.2.25 on 2025-10-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_backfill_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
